### PR TITLE
Velocity Implementation

### LINKED ISSUE #16: Velocity Support
Velocity is a Minecraft: Java Edition Proxy - more information about it at https://velocitypowered.com/

I believe that ChatSentinel having Velocity support would be really great as Velocity has been growing really quickly recently and having more great plugins such as CleanMOTD natively available on Velocity would be really good!

### PR DESCRIPTION
**Pull request by 4drian3d**
Resolves #16

### CODE REVIEW

**Comment by 4drian3d** [comment]
bump

**Comment by Pantera07** [comment]
https://jitpack.io/com/github/4drian3d/CleanMOTD/1219ad88f2/CleanMOTD-1219ad88f2.jar
It works fine.

**Comment by Pantera07** [comment]
Does cleanmotd performance better than velocity native motd?

**Comment by linsaftw** [comment]
> Does cleanmotd performance better than velocity native motd?

It never will. Native is always better.

**Comment by 4drian3d** [comment]
bump

**Pull request merged**
